--A list of material names to remove from the name of the base object
local materials = {
    ["adamantium"] = true,
    ["armor"] = true,
    ["bear"] = true,
    ["bonemold"] = true,
    ["chitin"] = true,
    ["chuzei"] = true,
    ["daedric"] = true,
    ["dwarven"] = true,
    ["ebony"] = true,
    ["fine"] = true,
    ["gah-julan"] = true,
    ["glass"] = true,
    ["huntsman"] = true,
    ["ice"] = true,
    ["iron"] = true,
    ["native"] = true,
    ["armun-an"] = true,
    ["nordic"] = true,
    ["orcish"] = true,
    ["redoran"] = true,
    ["reikling"] = true,
    ["silver"] = true,
    ["steel"] = true,
    ["throwing"] = true,
    ["wolf"] = true,
    ["wooden"] = true,
}
return materials