local prefixes = {
    {
        name = "Acrobat's",
        description = "+1 to Amazon Passive Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Amber",
        description = "Lightning resist 31-40%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Angel's",
        description = "+1 to Sorceress Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Archangel's",
        description = "+2 to Sorceress Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Archer's",
        description = "+3 to Amazon Bow and Crossbow Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Arcadian",
        description = "+51-100 to Attack Rating against Demons; Damage +26-50% against Demons",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Arching",
        description = "+1 minimum and +261-360 maximum lightning damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Artisan's",
        description = "Adds 3 Sockets",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Assamic",
        description = "+25-50 to Attack Rating against Demons; Damage +10-25% against Demons",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Astral",
        description = "+151-200 to Attack Rating against Demons; Damage +101-150% against Demons",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Athlete's",
        description = "+3 to Amazon Passive Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Azure",
        description = "Cold resist 5-10%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Bahamut's",
        description = "+91-120 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Berserker",
        description = "+2 to Barbarian Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Beryl",
        description = "Poison resist 5-10%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Blazing",
        description = "+2 to Sorceress Fire Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Blessed",
        description = "51-65% Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Blighting",
        description = "+2 to Necromancer Curses",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Boreal",
        description = "+16-23 minimum and +46-90 maximum Cold Damage for 3 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Boywer's",
        description = "+2 to Amazon Bow and Crossbow Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Bronze",
        description = "+10-20 Attack rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Brutal",
        description = "41-50% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Burgundy",
        description = "Fire resist 11-20%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Burning",
        description = "+1 to Sorceress Fire Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Buzzing",
        description = "+1 minimum and +181-260 maximum Lightning Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Captain's",
        description = "+1 to Paladin Offensive Auras",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Caretaker's",
        description = "+2 to Druid Summoning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Celestial",
        description = "+300-400 to Attack Rating against Demons; Damage +201-300% against Demons",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Charged",
        description = "+2 to Sorceress Lightning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Chilling",
        description = "+1 to Sorceress Cold Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Chromatic",
        description = "+21-30% to All Resistances",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Cobalt",
        description = "Cold resist 21-30%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Commander's",
        description = "+2 to Paladin Offensive Auras",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Communal",
        description = "+3 to Druid Shapeshifting Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Compact",
        description = "+20-40 Quantity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Condensing",
        description = "+121-170 minimum and +181-240 maximum Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Consecrated",
        description = "+25-75 to Attack Rating against Undead; Damage +25-75% against Undead",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Coral",
        description = "Lightning resist 21-30%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Corrosive",
        description = "+29 Poison Damage for 2 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Crimson",
        description = "Fire resist 5-10%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Cruel",
        description = "+201-300% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Cunning",
        description = "+3 to Assassin Traps",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Cursing",
        description = "+3 to Necromancer Curses",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Deadly",
        description = "21-30% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Dense",
        description = "+80-120 Quantity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Devious",
        description = "Magic damage reduced by 1",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Divine",
        description = "+326-450 to Attack Rating against Undead; Damage +276-350% against Undead",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Dragon's",
        description = "+31-40 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Drake's",
        description = "+21-30 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Echoing",
        description = "+3 to Barbarian Warcries",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Elysian",
        description = "+201-300 to Attack Rating against Demons; Damage +151-200% against Demons",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Emerald",
        description = "Poison resist 31-40%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Entrapping",
        description = "+1 to Assassin Traps",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Expert's",
        description = "+1 to Barbarian Combat Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Faithful",
        description = "+ (3 per character level/0.5 per character level) to Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fanatic",
        description = "+1 to Barbarian Combat Masteries",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Felicitous",
        description = "5-10% Better Chance of Getting Magic Item",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Feral",
        description = "+2 to Druid Shapeshifting Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Ferocious",
        description = "+101-200% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fine",
        description = "+21-40 to Attack rating; Damage 21-30%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Firey",
        description = "+16-25 minimum nad +31-60 maximum Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Flaming",
        description = "+81-120 minimum and +131-180 maximum to Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fletcher",
        description = "+1 to Amazon Bow and Crossbow Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fool's",
        description = "+ (16.5 per character level) to Attack Rating and + (0.5 per character level) to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fortified",
        description = "Magic damage reduced by 2",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fortuitous",
        description = "11-15% better chance of getting magic items",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Foul",
        description = "+15 Poison Damage for 2 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Freezing",
        description = "+2 to Sorceress Cold Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fungal",
        description = "+1 to Necromancer Poison and Bone Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Furious",
        description = "+3 to Barbarian Combat Masteries",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Garnet",
        description = "Fire resist 21-30%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Gaea's",
        description = "+3 to Druid Elemental Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Glacial",
        description = "+3 to Sorceress Cold Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Glimmering",
        description = "+1 to Light radius",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Glorious",
        description = "41-50% Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Glowing",
        description = "+1 minimum and +121-180 maximum LightningDamage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Godly",
        description = "+101-200% Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Gold",
        description = "+81-100 to Attack rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Golemlord's",
        description = "+3 to Necromancer Summoning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Grandmaster's",
        description = "+251-300 to Attack Rating; Damage +151-200%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Graverobber's",
        description = "+1 to Necromancer Summoning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Great Wyrm's",
        description = "+61-90 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Grinding",
        description = "+ 0.75 per character level to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Guardian's",
        description = "+3 to Paladin Defensive Auras",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Gymnast's",
        description = "+2 to Amazon Passive Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Hallowed",
        description = "+251-325 to Attack Rating against Undead; Damage +201-275% against Undead",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Harpoonist's",
        description = "+1 to Amazon Javelin and Spear Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Hawk-Branded",
        description = "+2 to Paladin Combat Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Hawkeye",
        description = "+1.5 to Attack Rating, based on Character Level",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Hexing",
        description = "+1 to Necromancer Curses",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Hibernal",
        description = "+24-45 minimum and +91-140 maximum Cold Damage for 4 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Hierophant's",
        description = "+2 to Druid Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Holy",
        description = "81-100% Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Howling",
        description = "Hit causes monsters to flee 18-50%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Iron",
        description = "+21-40 to Attack rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Jade",
        description = "Poison resist 21-30%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Jagged",
        description = "10-20% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Jeweler's",
        description = "Adds 3 Sockets",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Keeper's",
        description = "+3 to Druid Summoning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Kenshi's",
        description = "+3 to Assassin Martial Arts",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "King's",
        description = "+121-150 to Attack rating; Damage 81-100%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Knight's",
        description = "+81-100  to Attack rating; Damage 51-65%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lancer's",
        description = "+3 to Amazon Javelin and Spear Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lapis",
        description = "Cold resist 11-20%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lion-Branded",
        description = "+1 to Paladin Combat Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lizard's",
        description = "1-5 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lord's",
        description = "+101-120 to Attack rating; Damage 66-80%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lunar",
        description = "+25-50 to Attack Rating against Demons",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    { name = "+10-25% Damage against Demons" },
    {
        name = "Magekiller's",
        description = "+1 to Assassin Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Maiden's",
        description = "+1 to Amazon Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Marshall's",
        description = "+3 Paladin Offensive Auras",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Massive",
        description = "51-65% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Master's",
        description = "+151-250 to Attack Rating; Damage +101-150%(Weapons)",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    { name = "+3 to Barbarian Combat Skills (Amulets, Barbarian Helms, Weapons)" },
    {
        name = "Mechanist's",
        description = "Adds 1 Socket",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Mentalist's",
        description = "+1 to Assassin Shadow Disciplines",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Merciless",
        description = "81-100% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Meteoric",
        description = "+121-150 to Attack rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Mnemonic",
        description = "+ (0.5 per character level) to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Mojo",
        description = "+2 to Necromancer Summoning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Monk's",
        description = "+1 to Paladin Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Nature's",
        description = "+1 to Druid Elemental Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Necromancer's",
        description = "+2 to Necromancer Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Noxious",
        description = "+2 to Necromancer Poison and Bone Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Ocher",
        description = "Lightning resist 11-20%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Pestilent",
        description = "+275 Poison Damage for 2 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Platinum",
        description = "+101-120 to Attack rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Powered",
        description = "+3 to Sorceress Lighting Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Preserver's",
        description = "+1 to Paladin Defensive Auras",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Priest's",
        description = "+2 to Paladin Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Prismatic",
        description = "+16-20% to All Resistances",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Psychic",
        description = "+2 to Assassin Shadow Disciplines",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Pure",
        description = "+76-175 to Attack Rating against Undead; Damage +76-125% against Undead",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Raging",
        description = "+2 to Barbarian Combat Masteries",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Rainbow",
        description = "+8-11% to All Resistances",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Resonant",
        description = "+2 to Barbarian Warcries",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Rose-Branded",
        description = "+3 to Paladin Combat Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Ruby",
        description = "Fire resist 31-40%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Rugged",
        description = "+5-20 to max Stamina",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Russet",
        description = "+11-20 to Fire Resist",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sacred",
        description = "+175-250 to Attack Rating against Undead; Damage +126-200% against Undead",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Saintly",
        description = "66-80% Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sapphire",
        description = "Cold resist 31-40%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Savage",
        description = "66-80% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Scintillating",
        description = "+12-15% to All Resistances",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Screaming",
        description = "+ (0.75 per character level) to maximum Damage(Weapons)",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    { name = "Hit Causes Monsters to Flee, 12-25%(Bow, Crossbows, Weapons)" },
    {
        name = "Sensei's",
        description = "+2 to Assassin Martial Arts",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Septic",
        description = "+6 Poison Damage for 2 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Serpent's",
        description = "+11-20 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Shadow",
        description = "+3 to Assassin Shadow Disciplines",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Shaman's",
        description = "+1 to Druid Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sharp",
        description = "+10-20 to Attack rating; Damage 10-20%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Shimmering",
        description = "+3-7% to all Resistances",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Shivering",
        description = "+10-15 minimum and +31-45 maximum Cold Damage for 2 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Shocking",
        description = "+1 minimum and +361-480 maximum Lightning Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Shogukusha's",
        description = "+1 to Assassin Martial Arts",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Silver",
        description = "+61-80 to Attack rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Slayer",
        description = "+1 to Barbarian Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Smoking",
        description = "+51-80 minimum and +91-130 maximum Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Smoldering",
        description = "+26-50 minimum and +61-90 maximum Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Snake's",
        description = "5-10 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Snowy",
        description = "+6-9 minimum and +19-30 maximum Cold Damage for 1 second",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Soldier's",
        description = "+61-80 to Attack rating; Damage 41-50%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sounding",
        description = "+1 to Barbarian Warcries",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sparking",
        description = "+1 to Sorceress Lighting Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Spearmaiden's",
        description = "+2 to Amazon Javelin and Spear Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Spiritual",
        description = "+1 to Druid Shapeshifting Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Static",
        description = "+1 minimum and +49-120 Maximum Lightning Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Steel",
        description = "+41-60 to Attack rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Strange",
        description = "+151-300 to Attack Rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Strong",
        description = "31-40% Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sturdy",
        description = "10-30% Defense",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Summoner's",
        description = "+1 to Necromancer Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Tangerine",
        description = "Lightning resist 5-10%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Terrene",
        description = "+2 to Druid Elemental Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Thin",
        description = "+41-80 Quantity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Tireless",
        description = "Heal Stamina +25-50%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Toxic",
        description = "+150 Poison Damage for 5 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Trainer's",
        description = "+1 to Druid Summoning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Trickster's",
        description = "+2 to Assassin Traps",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Triumphant",
        description = "+1 point of Mana after each kill",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Unearthly",
        description = "+101-150 to Attack Rating against Demons; Damage +51-100% against Demons",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Valkyrie's",
        description = "+2 to Amazon Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Venomous",
        description = "+3 to Necromancer Poison and Bone Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Veteran's",
        description = "+2 to Barbarian Combat Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Vicious",
        description = "31-40% Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Victorious",
        description = "+2-5 Mana after each Kill",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Vigorous",
        description = "+21-30 to Maximum Stamina",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Viridian",
        description = "Poison resist 11-20%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Visionary",
        description = "+1 per character level to Armor Level",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Vodoun",
        description = "+2 to Necromancer Summoning Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Volcanic",
        description = "+3 to Sorceress Fire Skills",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Vulpine",
        description = "7-12% damage taken goes to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Wailing",
        description = "Hit Causes Monsters to Flee, 25-100%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Warder's",
        description = "+2 to Paladin Defensive Auras",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Warrior's",
        description = "+41-60 Attack rating;  Damage 31-40%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Weird",
        description = "+301-450 to Attack Rating",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Witch-hunter's",
        description = "+2 to Assassin Skill Levels",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Wyrm's",
        description = "+41-60 to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
}
return prefixes