local suffixes = {
    {
        name = "Absorption",
        description = "Damage reduced by 3",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Acceleration",
        description = "40% Faster run/walk",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Accuracy",
        description = "+6-9 to Dexterity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Ages",
        description = "Indestructible",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Alacrity",
        description = "20% Attack Rate increase",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Amelioration",
        description = "Poison length reduced by 50%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Amicae",
        description = "Damage reduced by 8-15",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Anima",
        description = "Damage Reduced by 8-15",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Anthrax",
        description = "Adds 100 Poison Damage for 6 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Apprentice",
        description = "10% Faster Cast Rate",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Atlas",
        description = "+21-30 to Strength",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Balance",
        description = "10% Faster Hit Recovery",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Bashing",
        description = "- 25-40 to Monster Defense per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Bat",
        description = "3-5% Mana stolen per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Bear",
        description = "Knockback",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Blight",
        description = "Add 50 Poison damage for 3 seconds (Rings/Amulets) \n Add 7 Poison damage for 3 seconds (Weapons/Circlets)",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Blocking",
        description = "+15% Faster Block Rate",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Brilliance",
        description = "+7-10 to Energy",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Burning",
        description = "Adds 5-9 minimum and 10-20 maximum Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Butchery",
        description = "+21-40 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Carnage",
        description = "+11-14 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Centaur",
        description = "+ (0.75 per character level) to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Chance",
        description = "5-15% better chance of getting magic item",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Colossus",
        description = "+41-60 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Craftsmanship",
        description = "+1 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Defiance",
        description = "Poison length reduced by 75%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Deflecting",
        description = "+30% Faster Block Rate",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Dexterity",
        description = "+1-2 to Dexterity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Ease",
        description = "Requirements -20%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Elephant",
        description = "+ (0.5 per character level) to Life and + (0.25 per character level) to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Energy",
        description = "+1-3 to Energy",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Enlightenment",
        description = "+21-30 to Energy",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Equilibrium",
        description = "17% Faster Hit Recovery",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Evisceration",
        description = "+41-63 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Excellence",
        description = "+5-8 to minimum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fast-Repair",
        description = "Repairs Durability",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fire",
        description = "Adds 1-4 minimum and 6-11 maximum to Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Flame",
        description = "Adds 1 minimum and 2-6 maximum to Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fortune",
        description = "16-25% better chance of getting magic item",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Fox",
        description = "+6-10 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Frost",
        description = "Adds 1 minimum and 1-2 maximum Cold Damage for 2 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Gargantuan",
        description = "+41-60 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Giant",
        description = "+10-15 to Strength",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Glacier",
        description = "Adds 2-4 minimum and 4-15 maximum Cold Damage for 4 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Gore",
        description = "+8-10 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Greed",
        description = "25-40% extra gold from monsters",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Guarding",
        description = "Magic damage reduced by 3",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Haste",
        description = "20% Faster run/walk",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Health",
        description = "Damage reduced by 1",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Icicle",
        description = "Adds 1 minimum and 3-4 maximum Cold Damage for 3 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Incineration",
        description = "Adds 10-15 minimum and 21-75 maximum Fire Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Jackal",
        description = "+1-5 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lamprey",
        description = "7-9% Life Stolen per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Leech",
        description = "3-5% Life stolen per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Life",
        description = "Damage reduced by 4-7",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Life Everlasting",
        description = "Damage Reduced by 10-25",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Light",
        description = "+1 to Light Radius, +15 to Armor Level",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Lightning",
        description = "Adds 1 minimum and 9-16 maximum Lightning Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Locust",
        description = "5-7% Life stolen per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Luck",
        description = "26-35% Better Chance of Getting Magic Items",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Magus",
        description = "20% Faster Cast Rate",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Maiming",
        description = "+3-4 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Mammoth",
        description = "+31-40 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Measure",
        description = "+3-4 to minimum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Memory",
        description = "+ (0.5 per character level) to Mana",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Might",
        description = "+3-5 to Strength",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Mind",
        description = "+4-6 to Energy",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Negation",
        description = "Magic damage reduced by 4-6",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Nirvana",
        description = "+21-30 to Dexterity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Ox",
        description = "+6-9 to Strength",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Pacing",
        description = "10% Faster run/walk",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Perfection",
        description = "+16-20 to Dexterity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Performance",
        description = "+9-14 to minimum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Pestilence",
        description = "Adds 50 Poison Damage for 5 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Piercing",
        description = "Ignores Target's defenses",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Precision",
        description = "+10-15 to Dexterity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Propagation",
        description = "Replenishes quantity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Protection",
        description = "Damage reduced by 2",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Puncturing",
        description = "- 10-20 to monster Defense per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Quality",
        description = "+2 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Quickness",
        description = "40% Attack Rate increase",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Radiance",
        description = "+3 to Light Radius, +30 to Armor Level",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Razors",
        description = "Attacker takes Damage of 7-9",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Readiness",
        description = "10% Attack Rate increase",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Regeneration",
        description = "Replenish Life +3-5",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Regrowth",
        description = "Replenish Life +6-10",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Remedy",
        description = "Poison length reduced by 25%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Replenishing",
        description = "Replenishes Quantity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Revivification",
        description = "Replenish Life +11-15",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Self-Repair",
        description = "Repairs Durability",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sentinel",
        description = "Magic damage reduced by 2",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Shock",
        description = "Adds 1 minimum and 6-8 maximum Lightning Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Simplicity",
        description = "Requirements -30%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Skill",
        description = "+3-5 to Dexterity",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Slaughter",
        description = "+15-20 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Slaying",
        description = "+5-7 to maximum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sorcery",
        description = "+11-15 to Energy",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Speed",
        description = "30% Faster run/walk",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Spikes",
        description = "Attacker takes 4-6 Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Squid",
        description = "+61-80 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Stability",
        description = "24% Faster Hit Recovery",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Storms",
        description = "Adds 1-6 minimum and 40-120 maximum Lightning Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Strength",
        description = "+1-2 to Strength",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Sun",
        description = "+5 to Light Radius, +5% bonus to Armor Level",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Swiftness",
        description = "30% Attack Rate increase",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Swords",
        description = "Attacker takes Damage of 10-20",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Thawing",
        description = "Half freeze duration",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Thorns",
        description = "Attacker takes 1-3 Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Thunder",
        description = "Adds 1 minimum and 17-40 maximum Lightning Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Tiger",
        description = "+21-30 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Titan",
        description = "+16-20 to Strength",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Transcendence",
        description = "+15-20 to minimum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Transportation",
        description = "30% faster Run/Walk +80-90% heal Stamina",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Traveling",
        description = "30% Faster run/walk, Heal Stamina +80-90%",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Vampire",
        description = "7-9% Mana stolen per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Venom",
        description = "Adds 21Poison Damage for 4 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Vileness",
        description = "Prevents monster heal",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Warding",
        description = "Magic damage reduced by 1",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Warmth",
        description = "Half Freeze Duration",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Wealth",
        description = "41-80% extra gold from monsters",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Whale",
        description = "+81-100 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Winter",
        description = "Adds 5-9 minimum and 16-50 maximum Cold Damage for 5 seconds",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Wizardry",
        description = "+16-20 to Energy",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Wolf",
        description = "+11-20 to Life",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Worth",
        description = "+1-2 to minimum Damage",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
    {
        name = "Wraith",
        description = "6-7% Mana Stolen per hit",
        effects = {},
        modifiers = {},
        rarity = "common",
        validWeaponTypes = {},
        validArmorTypes = {},
        validClothingTypes = {},
    },
}